### ISSUE TITLE
README Image

### ISSUE THREAD

**Issue by coffmark** [Ryosukekamimura/Gradient_Boost#1]
<img width="1680" alt="スクリーンショット 2020-08-17 16 56 31" src="https://user-images.githubusercontent.com/52638834/90451750-7ae4a380-e127-11ea-9d8d-82007dac354d.png">

**Comment by Ryosukekamimura** [comment]
<img width="1680" alt="スクリーンショット 2020-08-18 8 29 25" src="https://user-images.githubusercontent.com/52638834/90457724-58f31d00-e137-11ea-9a21-5d3a6a854336.png">
<img width="1680" alt="スクリーンショット 2020-08-18 9 41 39" src="https://user-images.githubusercontent.com/52638834/90457731-5db7d100-e137-11ea-991e-9ca5abd935d4.png">
